[package]
name = "tquic-mimic-chromium-client"
version = "0.1.7"
edition = "2024"
rust-version = "1.90.0"
license = "Apache-2.0"
repository = "https://github.com/jay-l-e-e/tquic"
homepage = "https://github.com/jay-l-e-e/tquic"
description = "A high-performance, lightweight, and cross-platform QUIC client that mimics chromium network stack"
keywords = ["quic"]
categories = ["network-programming"]
build = "src/build.rs"
include = [
    "/*.md",
    "/*.toml",
    "/LICENSE",
    "/src",
    "/include"
]

[package.metadata.docs.rs]
no-default-features = true
features = ["qlog"]

[features]
default = ["qlog"]

# build the FFI API
ffi = []

# enable support for the qlog
qlog = ["dep:serde", "dep:serde_derive", "dep:serde_with"]

[workspace.dependencies]
boring-sys-vendit = "0.0.3"
brotli = "8.0"
bytes = "1"
enumflags2 = "0.7"
env_logger = "0.11"
flate2 = "1.1"
futures = "0.3"
hex = "0.4"
lazy_static = "1"
libc = "0.2"
log = { version = "0.4", features = ["std"] }
lru = "0.16"
mio = { version = "1", features = ["net", "os-poll"] }
priority-queue = "2.7"
rand = "0.9"
ring = "0.17"
rustc-hash = "2"
serde_json = { version = "1.0", features = ["preserve_order"] }
sfv = "0.14"
slab = "0.4"
smallvec = { version = "1.15", features = ["serde", "union"] }
strum = "0.27"
strum_macros = "0.27"
url = "2.5"
zstd = "0.13"

[dependencies]
boring-sys-vendit.workspace = true
brotli.workspace = true
bytes.workspace = true
enumflags2.workspace = true
env_logger.workspace = true
flate2.workspace = true
futures.workspace = true
hex.workspace = true
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
lru.workspace = true
mio.workspace = true
priority-queue.workspace = true
rand.workspace = true
ring.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true
sfv.workspace = true
slab.workspace = true
smallvec.workspace = true
strum.workspace = true
strum_macros.workspace = true
url.workspace = true
zstd.workspace = true
serde = { version = "1.0", features = ["derive"], optional = true }
serde_derive = { version = "1.0", optional = true }
serde_with = { version="3.14", optional = true }

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = ["wincrypt", "ws2def", "ws2ipdef", "ws2tcpip"] }

[dev-dependencies]
tempfile = "3.5.0"
ctor = "0.6"
criterion = "0.7"
timer_heap = "0.3.0"

[build-dependencies]
cmake = "0.1"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[workspace]
members = ["tools"]
