[package]
name = "tquic_tools"
version = "0.0.1"
edition = "2024"
rust-version = "1.90.0"
license = "Apache-2.0"
repository = "https://github.com/tencent/tquic"
homepage = "https://tquic.net"
description = "TQUIC client and server tools"
keywords = ["quic"]
categories = ["network-programming"]

[dependencies]
brotli.workspace = true
bytes.workspace = true
env_logger.workspace = true
flate2.workspace = true
log.workspace = true
mio.workspace = true
rand.workspace = true
rustc-hash.workspace = true
slab.workspace = true
tquic-mimic-chromium-client = { path = ".." }
url.workspace = true
zstd.workspace = true
clap = { version = "4.5", features = ["derive"] }
signal-hook = "0.3"
statrs = "0.18"

[target."cfg(unix)".dependencies]
jemallocator = { version = "0.6", package = "tikv-jemallocator" }

[lib]
crate-type = ["lib"]
path = "src/common.rs"

[[bin]]
name="tquic_client"
path="src/bin/tquic_client.rs"
