// Copyright (c) 2023 The TQUIC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! A QUIC endpoint.

#![allow(unused_variables)]

use std::cell::RefCell;
use std::cmp;
use std::collections::HashMap;
use std::collections::VecDeque;
use std::net::SocketAddr;
use std::rc::Rc;
use std::time::Duration;
use std::time::Instant;

use bytes::Bytes;
use bytes::BytesMut;
use log::*;
use rand::Rng;
use ring::hmac;
use rustc_hash::FxHashMap;
use rustc_hash::FxHashSet;
use slab::Slab;

use crate::ConnectionId;
use crate::ConnectionIdGenerator;
use crate::ConnectionQueues;
use crate::Event;
use crate::FourTuple;
use crate::PacketInfo;
use crate::PacketSendHandler;
use crate::Result;
use crate::TransportHandler;
use crate::connection::Connection;
use crate::error::Error;
use crate::packet;
use crate::packet::PacketHeader;
use crate::packet::PacketType;
use crate::timer_queue::TimerQueue;
use crate::token::AddressToken;
use crate::token::AddressTokenType::*;
use crate::token::ResetToken;

/// Endpoint is an entity that can participate in a QUIC connection by
/// generating, receiving, and processing QUIC packets.
///
/// There are two types of endpoints in QUIC: client and server. Endpoint may
/// maintain one or more QUIC connections.  Endpoint provides a high level API
/// to use the QUIC library.
pub struct Endpoint {
    /// QUIC Configuration
    config: Box<crate::Config>,

    /// All connections on the endpoint.
    conns: ConnectionTable,

    /// Used for matching incoming packets to connections.
    routes: ConnectionRoutes,

    /// Connections ordered by expiration time.
    timers: TimerQueue,

    /// Various connection queues.
    queues: Rc<RefCell<ConnectionQueues>>,

    /// Connection ID Generator.
    cid_gen: Box<dyn ConnectionIdGenerator>,

    /// Used to communicate with the application code.
    handler: Box<dyn TransportHandler>,

    /// Used to send packet out.
    sender: Rc<dyn PacketSendHandler>,

    /// Buffer for ZeroRTT packets that arrive before Initial packets due to
    /// potential misordering or loss of Initial packets.
    buffer: PacketBuffer,

    /// Packets generated by the endpoint.
    packets: PacketQueue,

    /// The endpoint is shutdown.
    closed: bool,

    /// The unique trace id for the endpoint
    trace_id: String,
}

impl Endpoint {
    /// Create a QUIC endpoint.
    pub fn new(
        config: Box<crate::Config>,
        handler: Box<dyn TransportHandler>,
        sender: Rc<dyn PacketSendHandler>,
    ) -> Self {
        let cid_gen = Box::new(crate::RandomConnectionIdGenerator {
            // If client omits SCID, expect zero-length DCID on incoming short headers.
            cid_len: if config.omit_client_initial_scid() {
                0
            } else {
                config.cid_len
            },
        });
        let buffer = PacketBuffer::new(config.zerortt_buffer_size);
        let packets = PacketQueue::new(config.send_batch_size);

        Self {
            config,
            conns: ConnectionTable::new(),
            routes: ConnectionRoutes::new(),
            timers: TimerQueue::new(),
            queues: Rc::new(RefCell::new(ConnectionQueues::new())),
            cid_gen,
            handler,
            sender,
            buffer,
            packets,
            closed: false,
            trace_id: "CLIENT".to_string(),
        }
    }

    /// Create a client connection.
    /// Note: The `config` specific to the endpoint or server is irrelevant and will be disregarded.
    ///
    /// The caller should call `process_connections()` after one or more connect().
    pub fn connect(
        &mut self,
        local: SocketAddr,
        remote: SocketAddr,
        server_name: Option<&str>,
        session: Option<&[u8]>,
        token: Option<&[u8]>,
        config: Option<&crate::Config>,
    ) -> Result<u64> {
        if self.closed {
            return Err(Error::InvalidOperation("already closed".into()));
        }

        let config = if let Some(config) = config {
            config
        } else {
            &self.config
        };

        // Create a client connection.
        let scid = if config.omit_client_initial_scid() {
            // Use zero-length SCID so replies with zero-length DCID route by 4-tuple
            ConnectionId::default()
        } else {
            self.cid_gen.generate()
        };

        let conn_result = Connection::new_client(&scid, local, remote, server_name, config);

        if let Ok(conn) = conn_result {
            let idx = self.conns.insert(conn);
            if let Some(conn) = self.conns.get_mut(idx) {
                conn.set_index(idx);
                conn.set_queues(self.queues.clone());
                if let Some(session) = session {
                    conn.set_session(session)?;
                }
                if let Some(token) = token {
                    conn.set_token(token.to_vec())?;
                }

                conn.start_handshake()?;

                self.handler.on_conn_created(conn);
                conn.mark_tickable(true);
            }

            // Update the connection route.
            if !scid.is_empty() {
                self.routes.insert_with_cid(scid, idx);
            } else {
                self.routes
                    .insert_with_addr(FourTuple { local, remote }, idx);
            }

            Ok(idx)
        } else {
            error!("new client error: {:?}", conn_result.err().unwrap());

            Err(Error::InvalidOperation("new client error".into()))
        }
    }

    /// Process an incoming UDP datagram.
    ///
    /// Incoming packets are classified on receipt. Packets can either be
    /// associated with an existing connection or for servers potentially create
    /// a new connection.
    /// See RFC 9000 Section 5.2 Matching Packets to Connections.
    pub fn recv(&mut self, buf: &mut [u8], info: &PacketInfo) -> Result<()> {
        trace!(
            "{} recv packet {} bytes {:?}",
            &self.trace_id,
            buf.len(),
            info
        );

        let cid_len = self.cid_gen.cid_len();
        let (hdr, _) = PacketHeader::from_bytes(buf, cid_len)?;
        let (local, remote) = (info.dst, info.src);

        // Try to delivery the datagram to the target connection.
        if let (Some(c), reset) = self.routes.find(&hdr.dcid, buf, info)
            && let Some(conn) = self.conns.get_mut(*c)
        {
            conn.mark_tickable(true);
            // Detected a Stateless Reset packet for an existing connection
            if reset && self.config.stateless_reset {
                trace!(
                    "{} connection {:?} got stateless reset from {:?}",
                    &self.trace_id,
                    conn.trace_id(),
                    info
                );
                conn.reset();
                return Ok(());
            }

            conn.recv(buf, info).map(|_| ())?;
            return Ok(());
        }

        if self.config.stateless_reset {
            self.send_stateless_reset(buf.len(), &hdr.dcid, local, remote)?;
        }

        Ok(())
    }

    /// Decode and validate the address token.
    fn validate_address_token(
        &mut self,
        addr_token: &mut [u8],
        cli_addr: &SocketAddr,
        cli_pkt_dcid: &ConnectionId,
    ) -> Result<AddressToken> {
        let lifetime = self.config.address_token_lifetime;

        for key in &self.config.address_token_key {
            match AddressToken::decode(key, addr_token, cli_addr, cli_pkt_dcid, lifetime) {
                Ok(token) => return Ok(token),
                Err(Error::ExpiredToken) => return Err(Error::ExpiredToken),
                _ => continue, // try the next key
            }
        }
        Err(Error::InvalidToken)
    }

    /// Write an Version Negoiation packet which will be sent later.
    fn send_version_negotiation(
        &mut self,
        cli_pkt_hdr: &PacketHeader,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        let mut pkt_out = self.packets.get_buffer();
        let len =
            packet::version_negotiation(&cli_pkt_hdr.dcid, &cli_pkt_hdr.scid, &mut pkt_out[..])?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send version negotiation: remote {:?} local {:?}",
            &self.trace_id, remote, local
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Write an Retry packet which will be sent later.
    fn send_retry(
        &mut self,
        initial_pkt_hdr: &PacketHeader,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        let mut pkt_out = self.packets.get_buffer();

        // Generate a retry token
        let rscid = self.cid_gen.generate();
        let token = AddressToken::new_retry_token(remote, initial_pkt_hdr.dcid, rscid);
        let token = token.encode(&self.config.address_token_key[0])?;

        // Write a Retry packet
        let len = packet::retry(
            &rscid,                // server cid
            &initial_pkt_hdr.scid, // client cid
            &initial_pkt_hdr.dcid, // original dcid
            &token,
            crate::QUIC_VERSION_V1,
            &mut pkt_out[..],
        )?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send retry: remote {:?} local {:?}",
            &self.trace_id, remote, local
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Write an Stateless Reset packet which will be sent later.
    /// TODO: rate limit based on address
    fn send_stateless_reset(
        &mut self,
        pkt_in_len: usize,
        dcid: &ConnectionId,
        local: SocketAddr,
        remote: SocketAddr,
    ) -> Result<()> {
        // Endpoints MUST discard packets that are too small to be valid QUIC packets.
        // The smallest possible valid 1rtt packet is: 1 byte of header + cid_len +
        // 1 byte of packet number + 1 byte of payload + 16 bytes of AEAD overhead.
        if pkt_in_len < self.cid_gen.cid_len() + 19 {
            return Ok(());
        }

        // Generate a stateless reset that is as short as possible, but long enough
        // to be difficult to distinguish from one rtt packets.
        let pkt_out_len = pkt_in_len - 1;
        if pkt_out_len < crate::MIN_RESET_PACKET_LEN {
            return Ok(());
        }
        let pkt_out_len = cmp::min(pkt_out_len, crate::MAX_RESET_PACKET_LEN);

        // Generate stateless reset token based on the dcid.
        let key = &self.config.reset_token_key;
        let reset_token = ResetToken::generate(key, dcid);

        // Write a Stateless Reset packet.
        let mut pkt_out = self.packets.get_buffer();
        let len = packet::stateless_reset(pkt_out_len, &reset_token, &mut pkt_out[..])?;
        pkt_out.truncate(len);

        let pkt_info = PacketInfo {
            src: local,
            dst: remote,
            time: Instant::now(),
        };

        trace!(
            "{} send Stateless Reset {:?} token={:?} dcid_pkt_in={:?}",
            &self.trace_id, pkt_info, reset_token, dcid,
        );
        self.packets.add_packet(pkt_out, pkt_info);
        Ok(())
    }

    /// Return the amount of time until the next timeout event.
    pub fn timeout(&self) -> Option<Duration> {
        // There are still events pending
        let queues = self.queues.borrow();
        if !self.packets.is_empty() || !queues.is_empty() {
            return Some(crate::TIMER_GRANULARITY);
        }

        self.timers.time_remaining(Instant::now())
    }

    /// Process timeout events on the endpoint.
    pub fn on_timeout(&mut self, now: Instant) {
        while let Some(idx) = self.timers.next_expire(now) {
            if let Some(conn) = self.conns.get_mut(idx) {
                trace!(
                    "{} process timeout event, connection index {} trace id {}",
                    self.trace_id,
                    idx,
                    conn.trace_id(),
                );
                conn.mark_tickable(true);
                conn.on_timeout(now);
            }
        }
    }

    /// Process internal events of all tickable connections.
    pub fn process_connections(&mut self) -> Result<()> {
        trace!(
            "{} process {} tickable connections",
            &self.trace_id,
            self.conn_tickable_len()
        );
        let mut ready = Vec::<u64>::new();

        // Process all tickable connections
        while let Some(idx) = self.conn_tickable_next() {
            if self.process_connection(idx, &mut ready) {
                continue;
            }

            // Try to clean up the closed connection.
            let conn = match self.conns.get_mut(idx) {
                Some(v) => v,
                None => continue,
            };

            for stream_id in conn.stream_iter() {
                self.handler.on_stream_closed(conn, stream_id);
                conn.stream_destroy(stream_id);
            }

            self.handler.on_conn_closed(conn);
            conn.mark_tickable(false);
            conn.mark_sendable(false);
            self.timers.del(&idx);
            self.routes.remove(conn);
            self.conns.remove(idx);
        }

        // Process all sendable connections
        self.send_packets_out()?;

        // Add connection with internal events to the tickable queue again.
        for idx in ready {
            if let Some(conn) = self.conns.get_mut(idx) {
                conn.mark_tickable(true);
            }
        }

        Ok(())
    }

    /// Process internal events of a tickable connection.
    ///
    /// Return `true` if the connection has been processed successfully.
    /// Return `false` if the connection has been closed and need to be cleaned up.
    fn process_connection(&mut self, idx: u64, ready: &mut Vec<u64>) -> bool {
        let conn = match self.conns.get_mut(idx) {
            Some(v) => v,
            None => return true,
        };
        if conn.is_closed() {
            return false;
        }

        // Try to process endpoint-facing events on the connection.
        while let Some(event) = conn.poll() {
            match event {
                Event::ConnectionEstablished => self.handler.on_conn_established(conn),

                Event::NewToken(token) => self.handler.on_new_token(conn, token),

                Event::ScidToAdvertise(num) => {
                    let key = &self.config.reset_token_key;
                    Self::conn_add_scids(conn, num, &mut self.cid_gen, key, &mut self.routes);
                }

                Event::ScidRetired(cid) => self.routes.remove_with_cid(&cid),

                Event::DcidAdvertised(token) => self.routes.insert_with_token(token, idx),

                Event::DcidRetired(token) => self.routes.remove_with_token(&token),

                Event::ResetTokenAdvertised(token) => self.routes.insert_with_token(token, idx),

                Event::StreamCreated(stream_id) => self.handler.on_stream_created(conn, stream_id),

                Event::StreamClosed(stream_id) => {
                    self.handler.on_stream_closed(conn, stream_id);
                    conn.stream_destroy(stream_id);
                }
            }
            if conn.is_closed() {
                return false;
            }
        }
        for stream_id in conn.stream_readable_iter() {
            if conn.stream_check_readable(stream_id) {
                self.handler.on_stream_readable(conn, stream_id);
                if conn.is_closed() {
                    return false;
                }
            }
        }
        for stream_id in conn.stream_writable_iter() {
            if conn.stream_check_writable(stream_id) {
                self.handler.on_stream_writable(conn, stream_id);
                if conn.is_closed() {
                    return false;
                }
            }
        }

        // Add the connection to the sendable queue
        conn.mark_sendable(true);

        // Try to update the timer of the connection
        if let Some(t) = conn.timeout() {
            self.timers.add(idx, t, Instant::now());
        } else {
            self.timers.del(&idx);
        }

        if conn.is_ready() {
            trace!("conn {} is still ready", conn.trace_id());
            ready.push(idx);
        }
        conn.mark_tickable(false);
        true
    }

    /// Add scids for the given connection
    fn conn_add_scids(
        conn: &mut Connection,
        num: u8,
        generator: &mut Box<dyn ConnectionIdGenerator>,
        token_key: &hmac::Key,
        routes: &mut ConnectionRoutes,
    ) {
        for i in 0..num {
            let (scid, reset_token) = generator.generate_cid_and_token(token_key);

            if conn.zero_length_scid() {
                break;
            }

            match conn.add_scid(scid, reset_token, true) {
                Ok(_) => (),
                Err(e) => {
                    warn!("add scid to {:?} : {:?}", conn.trace_id(), e);
                    break;
                }
            }

            let index = conn.index().unwrap();
            routes.insert_with_cid(scid, index);
        }
    }

    /// Check whether the given connection exists.
    pub(crate) fn conn_exist(&self, cid: ConnectionId) -> bool {
        self.routes.cid_table.contains_key(&cid)
    }

    /// Get the connection by index
    pub fn conn_get_mut(&mut self, index: u64) -> Option<&mut Connection> {
        match self.conns.get_mut(index) {
            Some(v) => Some(v), // `Box<&mut Connection>` is convert to `&mut Connection`
            None => None,
        }
    }

    /// Return the index of a tickable connection
    fn conn_tickable_next(&mut self) -> Option<u64> {
        let queues = self.queues.borrow_mut();
        queues.tickable_next()
    }

    /// Return the number of tickable connections
    fn conn_tickable_len(&self) -> usize {
        let queues = self.queues.borrow();
        queues.tickable.len()
    }

    /// Return the index of a sendable connection
    fn conn_sendable_next(&mut self) -> Option<u64> {
        let queues = self.queues.borrow_mut();
        queues.sendable_next()
    }

    /// Return the number of sendble connections
    fn conn_sendable_len(&self) -> usize {
        let queues = self.queues.borrow();
        queues.sendable.len()
    }

    /// Send the QUIC packets out to the peer.
    fn send_packets_out(&mut self) -> Result<()> {
        trace!(
            "{} process {} sendable connections",
            &self.trace_id,
            self.conn_sendable_len()
        );
        let mut sent = FxHashSet::default();
        let mut total = 0;

        while self.conn_sendable_len() > 0 {
            // Iterate over connections that have packets to send.
            while let Some(idx) = self.conn_sendable_next() {
                if let Some(conn) = self.conns.get_mut(idx) {
                    if conn.is_draining() || conn.is_closed() {
                        conn.mark_sendable(false);
                        continue;
                    }

                    let mut buf = self.packets.get_buffer();
                    match conn.send(&mut buf) {
                        Ok((len, info)) => {
                            buf.truncate(len);
                            self.packets.add_packet(buf, info);
                            sent.insert(idx);
                        }
                        Err(Error::Done) => {
                            self.packets.put_buffer(buf);
                            // Return Err(Error::Done) it means we can not send packets right now,
                            // but we still need to update timers for other events (e.g. Timer::Pacer)
                            sent.insert(idx);
                            // When a connection runs out of packets to send,
                            // it is removed from the sendable queue.
                            conn.mark_sendable(false);
                        }
                        Err(e) => {
                            self.packets.put_buffer(buf);
                            error!("{} generate packet err: {:?}", &self.trace_id, e);
                            return Err(e);
                        }
                    };
                }

                if self.packets.has_full_batch() {
                    let batch = self.packets.next_batch();
                    let done = match self.sender.on_packets_send(batch) {
                        Ok(v) => v,
                        Err(e) => {
                            error!("{} send packet err: {:?}", &self.trace_id, e);
                            return Err(e);
                        }
                    };
                    self.packets.drain_front(done);
                    total += done;
                };
            }
        }

        // Try to update timers
        for idx in &sent {
            if let Some(conn) = self.conns.get_mut(*idx) {
                if let Some(t) = conn.timeout() {
                    self.timers.add(*idx, t, Instant::now());
                } else {
                    self.timers.del(idx);
                }
            }
        }

        // Try to send the remaining packets
        let mut batch = self.packets.next_batch();
        while !batch.is_empty() {
            trace!(
                "{} try to send remaining packets in packet queue",
                &self.trace_id,
            );

            let done = self.sender.on_packets_send(batch)?;
            if done == 0 {
                break;
            }
            total += done;
            self.packets.drain_front(done);
            batch = self.packets.next_batch();
        }

        trace!("{} send total {} packets out", &self.trace_id, total);
        Ok(())
    }

    /// Gracefully or forcibly shutdown the endpoint.
    /// If `force` is false, cease creating new connections and wait for all
    /// active connections to close. Otherwise, forcibly close all the active
    /// connections.
    pub fn close(&mut self, force: bool) {
        self.closed = true;
        if !force {
            return;
        }

        trace!(
            "{} forcibly close {} connections",
            &self.trace_id,
            self.conns.len()
        );
        for (_, conn) in self.conns.conns.iter_mut() {
            for stream_id in conn.stream_iter() {
                self.handler.on_stream_closed(conn, stream_id);
                conn.stream_destroy(stream_id);
            }
            self.handler.on_conn_closed(conn);
        }
        self.timers.clear();
        self.routes.clear();
        self.conns.clear();
    }

    /// Set the connection id generator
    /// By default, the RandomConnectionIdGenerator is used.
    pub fn set_cid_generator(&mut self, cid_gen: Box<dyn ConnectionIdGenerator>) {
        self.cid_gen = cid_gen;
    }

    /// Set the unique trace id for the endpoint
    pub fn set_trace_id(&mut self, trace_id: String) {
        self.trace_id = trace_id
    }

    /// Return the unique trace id for the endpoint
    pub fn trace_id(&self) -> &str {
        &self.trace_id
    }
}

/// ConnectionTable is used for storing QUIC connections.
/// It provide pointer stability (the address of connections stored in the map
/// does not change), which makes the FFI API more easier to use.
struct ConnectionTable {
    conns: FxHashMap<u64, Box<Connection>>,
    next_index: u64,
}

impl ConnectionTable {
    fn new() -> Self {
        Self {
            conns: FxHashMap::default(),
            next_index: 0,
        }
    }

    /// Insert a QUIC connection
    fn insert(&mut self, conn: Connection) -> u64 {
        let index = self.next_index;
        self.next_index += 1;

        self.conns.insert(index, Box::new(conn));
        index
    }

    /// Get a QUIC connection by index
    fn get_mut(&mut self, index: u64) -> Option<&mut Box<Connection>> {
        self.conns.get_mut(&index)
    }

    /// Remove a QUIC connection by index
    fn remove(&mut self, index: u64) {
        self.conns.remove(&index);
    }

    /// Clear the connection table
    fn clear(&mut self) {
        self.conns.clear();
    }

    /// Return the number of connections
    fn len(&self) -> usize {
        self.conns.len()
    }

    /// Return true if there are no connections stored in the table.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// ConnectionRoutes is used for matching incoming packets to connections.
/// See RFC 9000 Section 5.2
struct ConnectionRoutes {
    /// Connections identified based on the locally created CID.
    cid_table: FxHashMap<ConnectionId, u64>,

    /// Connections(with zero-length CID) identified based on the address tuple.
    addr_table: HashMap<FourTuple, u64>,

    /// Connections identified based on the stateless reset token.
    token_table: FxHashMap<ResetToken, u64>,
}

impl ConnectionRoutes {
    fn new() -> Self {
        Self {
            cid_table: FxHashMap::default(),
            addr_table: HashMap::default(),
            token_table: FxHashMap::default(),
        }
    }

    /// Find the target connection for the incoming datagram.
    fn find(&self, dcid: &ConnectionId, buf: &mut [u8], info: &PacketInfo) -> (Option<&u64>, bool) {
        let mut reset = false;
        let mut idx = if !dcid.is_empty() {
            // The packet has a non-zero-length Destination Connection ID
            // corresponding to an existing connection.
            self.cid_table.get(dcid)
        } else {
            // The Destination Connection ID is zero length and the
            // addressing information in the packet matches the addressing
            // information the endpoint uses to identify a connection with a
            // zero-length connection ID.
            let addr = FourTuple {
                local: info.dst,
                remote: info.src,
            };
            self.addr_table.get(&addr)
        };

        if idx.is_none() && buf.len() > crate::RESET_TOKEN_LEN {
            // The endpoint identifies a received datagram as a Stateless Reset
            // by comparing the last 16 bytes of the datagram with all stateless
            // reset tokens.
            let token = match ResetToken::from_bytes(buf) {
                Ok(t) => t,
                Err(_) => return (None, false),
            };
            idx = self.token_table.get(&token);
            if idx.is_some() {
                reset = true;
            }
        }

        (idx, reset)
    }

    /// Insert the local cid and the connection.
    fn insert_with_cid(&mut self, cid: ConnectionId, idx: u64) {
        self.cid_table.insert(cid, idx);
    }

    /// Remove the entry for the given cid.
    fn remove_with_cid(&mut self, cid: &ConnectionId) {
        self.cid_table.remove(cid);
    }

    /// Insert the address tuple and the connection.
    fn insert_with_addr(&mut self, addr: FourTuple, idx: u64) {
        self.addr_table.insert(addr, idx);
    }

    /// Remove the entry for the given address tuple.
    fn remove_with_addr(&mut self, addr: &FourTuple) {
        self.addr_table.remove(addr);
    }

    /// Insert the stateless reset token and the connection.
    fn insert_with_token(&mut self, token: ResetToken, idx: u64) {
        self.token_table.insert(token, idx);
    }

    /// Remove the entry for the given reset token.
    fn remove_with_token(&mut self, token: &ResetToken) {
        self.token_table.remove(token);
    }

    /// Remove all routes for the connection
    fn remove(&mut self, conn: &Connection) {
        // Remove routes based on scid or address tuple
        if !conn.zero_length_scid() {
            for c in conn.scid_iter() {
                self.remove_with_cid(&c.cid);
            }
        } else {
            for ref p in conn.paths_iter() {
                self.remove_with_addr(p);
            }
        }

        // Remove routes based on stateless reset token
        if !conn.zero_length_dcid() {
            for c in conn.dcid_iter() {
                if let Some(token) = c.reset_token {
                    let token = ResetToken(token.to_be_bytes());
                    self.remove_with_token(&token);
                }
            }
        }
    }

    /// Clear all the routes.
    fn clear(&mut self) {
        self.cid_table.clear();
        self.addr_table.clear();
        self.token_table.clear();
    }
}

const MAX_ZERORTT_PACKETS_PER_CONN: usize = 10;

/// PacketBuffer is used for buffering early incoming ZeroRTT packets on the server.
/// Buffered packets are indexed by odcid.
struct PacketBuffer {
    packets: lru::LruCache<ConnectionId, Vec<(Vec<u8>, PacketInfo)>>,
}

impl PacketBuffer {
    fn new(cache_size: usize) -> Self {
        let size = std::num::NonZeroUsize::new(cache_size).unwrap();
        Self {
            packets: lru::LruCache::new(size),
        }
    }

    /// Buffer a ZeroRTT packet for the given connection
    fn add(&mut self, dcid: ConnectionId, buffer: Vec<u8>, info: PacketInfo) {
        if let Some(v) = self.packets.get_mut(&dcid) {
            if v.len() < MAX_ZERORTT_PACKETS_PER_CONN {
                v.push((buffer, info));
            }
            return;
        }

        let mut v = Vec::with_capacity(MAX_ZERORTT_PACKETS_PER_CONN);
        v.push((buffer, info));
        self.packets.put(dcid, v);
    }

    /// Remove all packets for the specified connection
    fn del(&mut self, dcid: &ConnectionId) -> Option<Vec<(Vec<u8>, PacketInfo)>> {
        self.packets.pop(dcid)
    }
}

const MAX_BUFFER_SIZE: usize = 2048;

/// PacketQueue is used for sending out packets in batches.
struct PacketQueue {
    /// Outgoing packets generated by the endpoint.
    packets: VecDeque<(Vec<u8>, PacketInfo)>,

    /// The batch size of outgoing packets.
    batch_size: usize,

    /// Send buffer pool.
    buffers: VecDeque<Vec<u8>>,
}

impl PacketQueue {
    fn new(batch_size: usize) -> Self {
        Self {
            packets: VecDeque::new(),
            batch_size,
            buffers: VecDeque::new(),
        }
    }

    /// check whether the packet queue is empty.
    fn is_empty(&self) -> bool {
        self.packets.len() == 0
    }

    /// Add a packet to queue for sending in batches.
    fn add_packet(&mut self, pkt: Vec<u8>, info: PacketInfo) {
        self.packets.push_back((pkt, info));
    }

    /// Return the next batch packets to send.
    fn next_batch(&mut self) -> &[(Vec<u8>, PacketInfo)] {
        let batch_size = cmp::min(self.batch_size, self.packets.len());
        self.packets.make_contiguous();
        let (packets, _) = self.packets.as_slices();
        &packets[..batch_size]
    }

    /// Check whether the number of packets reaches batch_size.
    fn has_full_batch(&self) -> bool {
        self.packets.len() >= self.batch_size
    }

    /// Remove the sent packets and put the used buffers to the buffer pool.
    fn drain_front(&mut self, n: usize) {
        let len = cmp::min(n, self.packets.len());
        for mut p in self.packets.drain(..len) {
            p.0.resize(MAX_BUFFER_SIZE, 0);
            self.buffers.push_back(p.0);
        }
    }

    /// Get a packet buffer from the buffer pool.
    fn get_buffer(&mut self) -> Vec<u8> {
        match self.buffers.pop_front() {
            Some(v) => v,
            None => vec![0; MAX_BUFFER_SIZE],
        }
    }

    /// Get a packet buffer from the buffer pool.
    fn put_buffer(&mut self, mut buf: Vec<u8>) {
        buf.resize(MAX_BUFFER_SIZE, 0);
        self.buffers.push_back(buf);
    }
}
